### PR TITLE
chore: add workaround for vpm-resolver's bug

### PR DESCRIPTION
**Pull request by anatawa12**
I don't know which license is used in this repository but I waive copyright of this patch if needed.

- https://github.com/vrchat-community/creator-companion/issues/226

### CODE REVIEW

**Comment by anatawa12** [comment]
See https://anatawa12.github.io/template-package-listing/index.json for changes of this branch.

**Comment by momo-the-monster** [comment]
Hm - I appreciate the effort you put in, but I don't really want all listings to add `?` to their URLs to deal with a bug we've now fixed. Just need to get everyone onto the newer resolvers.

**Comment by anatawa12** [comment]
For new projects, that's ok enough but how do we feel if we're checking old projects for reference (not for building)? I think we should support wide range as possible if it's easy.

**Comment by anatawa12** [comment]
In addition, We cannot use vpm-resolver v0.1.18 because of vrchat-community/creator-companion#254 so I still using vpm-resolver v0.1.17 in many projects.

Also, to upgrade vpm-resolver from v0.1.17 to v0.1.18, '?' is required in vpm-resolver.

**Comment by anatawa12** [comment]
I believe workaround is needed to upgrade vpm-resolver itself so I made this option optional.

**Pull request closed without merging**
