### PR TITLE
Fix things with a few params

### LINKED ISSUE #15: [FEATURE] make the "listing" string configurable
https://github.com/vrchat-community/package-list-action/blob/a3c757b0e77e90af5db7a41183f0dec24710366f/PackageBuilder/Build.cs#L87

Id love for this string to be configurable so I can make it more specific to my project. in my case I want to change it to something like "system" or "library" instead of "listing", but I cant do that unless I fork and use a custom version right now

### PR DESCRIPTION
**Pull request by Happyrobot33**
Adds a suffix to the package listing
Fixed the ability to set CurrentListingUrl to another URL. I needed to fix this in order for my custom domain to work

closes https://github.com/vrchat-community/package-list-action/issues/15

### CODE REVIEW

**Comment by Happyrobot33** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Happyrobot33** [comment]
recheck

**Comment by anatawa12** [comment]
I think it's better to have configurable name than configurable suffix.

**Comment by Spokeek** [comment]
Agreed, i would be more into customizing the list name as a whole instead of changing prefixes and suffixes.

**Comment by Spokeek** [comment]
Also, maybe change the PR name to something like "Make Package Listing Name configurable" ?

**Comment by Happyrobot33** [comment]
Closing to make a new PR with just these changes using a new branch on my fork

**Pull request closed without merging**
